mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/try/', views.logi, name='logi'),
    path('signup/regis', views.regis, name='regis')
]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    short_desc = models.CharField(max_length=200, null=True)
    long_desc = models.CharField(max_length=500, null=True)
    total_votes = models.IntegerField(default=0)

    def showable(self):
        return timezone.now() - self.pub_date < datetime.timedelta(days=1)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    percent = models.FloatField(default=0)

    def __str__(self):
        return self.choice_text


class Voted(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

mysite/polls/views.py
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice, Voted
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse


class SignupView(generic.TemplateView):
    template_name = 'polls/signup.html'


class LoginView(generic.TemplateView):
    template_name = 'polls/login.html'


class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/polls/login/'
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = '/polls/login/'
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(LoginRequiredMixin, generic.DetailView):
    login_url = '/polls/login/'
    model = Question
    template_name = 'polls/results.html'


@login_required(login_url='/polls/login/')
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        question.total_votes += 1
        question.save()
        for choice in question.choice_set.all():
            choice.percent = round(choice.votes * 100 / question.total_votes, 2)
            choice.save()
        voted = Voted(question=question, user=request.user)
        voted.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def regis(request):
    username = request.POST['username']
    password = request.POST['password']
    if User.objects.filter(username=username):
        return render(request, 'polls/signup.html', {'message': 'This username already used. Choose other one', })
    else:
        User.objects.create_user(username, None, password)
        return HttpResponseRedirect(reverse('polls:login'))


def logi(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('polls:index'))
    else:
        return render(request, 'polls/login.html', {'message': 'Incorrect username or password', })


def logout_view(request):
    logout(request)
    return render(request, 'polls/login.html', {'message': 'You are successfully logged out', })

mysite/polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<p>Your username - {{ user }}  <a href="{% url 'polls:logout_view' %}">Log-out</a></p>
{% if question.showable %}
    <h1>{{ question.question_text }}</h1>
    <p>{{ question.long_desc }}</p>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>
{% else %}
    <p>This poll is over</p>
{% endif %}
<a href="{% url 'polls:index' %}">To the main?</a>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<p>Your username - {{ user }}  <a href="{% url 'polls:logout_view' %}">Log-out</a></p>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        {% if question.showable %}
            <li><a href="{%url 'polls:detail' question.id %}">{{ question.question_text }}</a><br>
            <p>{{ question.short_desc }}</p></li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/login.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<h1>Log-in</h1>
{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
<form action="{% url 'polls:logi' %}" method="post">
{% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" id="username" required><br>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required><br>
    <input type="submit" value="Log-in">
</form>
<br><p><a href="{% url 'polls:login' %}">Log-in</a> | <a href="{% url 'polls:signup' %}">Sign-up</a></p>

mysite/polls/templates/polls/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<p>Your username - {{ user }}  <a href="{% url 'polls:logout_view' %}">Log-out</a></p>
{% if question.showable %}
    <h1>{{ question.question_text }}</h1>
    <p>Total votes - {{ question.total_votes }}</p>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} - {{ choice.percent }}%</li>
    {% endfor %}
    </ul>
{% else %}
    <p>This poll is over</p>
{% endif %}
<a href="{% url 'polls:index' %}">To the main?</a>

mysite/polls/templates/polls/signup.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<h1>Sign-up</h1>
{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
<form action="{% url 'polls:regis' %}" method="post">
{% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" id="username" required><br>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required><br>
    <input type="submit" value="Sign-up">
</form>
<br><p><a href="{% url 'polls:login' %}">Log-in</a> | <a href="{% url 'polls:signup' %}">Sign-up</a></p>